/* ========================================================================
 * Copyright 2014 monitor
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 monitor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/
define(['controller/_championShipController','delegate/championShipDelegate'], function() {
    App.Controller.ChampionShipController = App.Controller._ChampionShipController.extend({
        language: function(){
            alert('Usted está viendo la versión en ESPAÑOL de esta página');
        },
        cost: function(params)
        {
            
        function daysBetween(date1, date2)
        { 
           if (date1.indexOf("-") != -1) { date1 = date1.split("-"); } else if (date1.indexOf("/") != -1) { date1 = date1.split("/"); } else { return 0; } 
           if (date2.indexOf("-") != -1) { date2 = date2.split("-"); } else if (date2.indexOf("/") != -1) { date2 = date2.split("/"); } else { return 0; } 
           if (parseInt(date1[0], 10) >= 1000) { 
               var sDate = new Date(date1[0]+"/"+date1[1]+"/"+date1[2]);
           } else if (parseInt(date1[2], 10) >= 1000) { 
               var sDate = new Date(date1[2]+"/"+date1[0]+"/"+date1[1]);
           } else { 
               return 0; 
           } 
           if (parseInt(date2[0], 10) >= 1000) { 
               var eDate = new Date(date2[0]+"/"+date2[1]+"/"+date2[2]);
           } else if (parseInt(date2[2], 10) >= 1000) { 
               var eDate = new Date(date2[2]+"/"+date2[0]+"/"+date2[1]);
           } else { 
               return 0; 
           } 
           var one_day = 1000*60*60*24; 
           var daysApart = Math.abs(Math.ceil((sDate.getTime()-eDate.getTime())/one_day)); 
           return daysApart; 
        }
        
            var dias= daysBetween(params.startDate,params.endDate);
            var costo= Math.pow(Math.E,(0.5* dias));
            alert("La duracion en dias es: "+ dias+" Y el costo total sera: "+ costo+".");
        }
    });
    return App.Controller.ChampionShipController;
}); 